var song_list = {
    "1" : {
        title: "As if it's your last",
        artist: "BLACKPINK",
        genre: "Kpop",
        duration: "3:33",
        track: "BLACKPINK - AS IF IT'S YOUR LAST.mp3",
    },
    "2" : {
        title: "Ddu-Du Ddu-Du",
        artist: "BLACKPINK",
        genre: "Kpop",
        duration: "3:27",
        track: "BLACKPINK - DDU-DU DDU-DU.mp3",
    },
    "3" : {
        title: "How You Like That",
        artist: "BLACKPINK",
        genre: "Kpop",
        duration: "2:59",
        track: "BLACKPINK - How You Like That.mp3",
    },
    "4" : {
        title: "Boy With Luv",
        artist: "BTS",
        genre: "Kpop",
        duration: "3:52",
        track: "BTS - Boy With Luv.mp3",
    },
    "5" : {
        title: "Butter",
        artist: "BTS",
        genre: "Kpop",
        duration: "2:58",
        track: "BTS - Butter.mp3",
    },
    "6" : {
        title: "Dynamite",
        artist: "BTS",
        genre: "Kpop",
        duration: "3:24",
        track: "BTS - Dynamite.mp3",
    },
    "7" : {
        title: "Fake Love",
        artist: "BTS",
        genre: "Kpop",
        duration: "4:00",
        track: "BTS - FAKE LOVE.mp3",
    },
    "8" : {
        title: "Fire",
        artist: "BTS",
        genre: "Kpop",
        duration: "3:28",
        track: "BTS - Fire.mp3",
    },
    "9" : {
        title: "IDOL",
        artist: "BTS",
        genre: "Kpop",
        duration: "3:56",
        track: "BTS - IDOL.mp3",
    },
    "10" : {
        title: "Ko Ko Bop",
        artist: "EXO",
        genre: "Kpop",
        duration: "3:13",
        track: "EXO - Ko Ko Bop.mp3",
    },
    "11" : {
        title: "Love Shot",
        artist: "EXO",
        genre: "Kpop",
        duration: "3:26",
        track: "EXO - Love Shot.mp3",
    },
    "12" : {
        title: "Me Gustas Tu",
        artist: "GFRIEND",
        genre: "Kpop",
        duration: "3:41",
        track: "G-Friend - Me Gustas Tu.mp3",
    },
    "13" : {
        title: "Love Scenario",
        artist: "IKON",
        genre: "Kpop",
        duration: "3:28",
        track: "iKON - Love Scenario.mp3",
    },
    "14" : {
        title: "Dalla Dalla",
        artist: "ITZY",
        genre: "Kpop",
        duration: "3:16",
        track: "ITZY - DALLA DALLA.mp3",
    },
    "15" : {
        title: "La Vie En Rose",
        artist: "IZ*ONE",
        genre: "Kpop",
        duration: "3:28",
        track: "IZ_ONE - La Vie en Rose.mp3",
    },
    "16" : {
        title: "Lalisa",
        artist: "LISA",
        genre: "Kpop",
        duration: "3:21",
        track: "LISA - LALISA.mp3",
    },
    "17" : {
        title: "Money",
        artist: "LISA",
        genre: "Kpop",
        duration: "2:48",
        track: "LISA - MONEY.mp3",
    },
    "18" : {
        title: "Hip",
        artist: "MAMAMOO",
        genre: "Kpop",
        duration: "3:28",
        track: "MAMAMOO - HIP.mp3",
    },
    "19" : {
        title: "Gashina",
        artist: "SUNMI",
        genre: "Kpop",
        duration: "2:57",
        track: "SUNMI - GASHINA.mp3",
    },
    "20" : {
        title: "Cheer Up",
        artist: "TWICE",
        genre: "Kpop",
        duration: "3:28",
        track: "TWICE - CHEER UP.mp3",
    },
    "21" : {
        title: "Fancy",
        artist: "TWICE",
        genre: "Kpop",
        duration: "3:36",
        track: "TWICE - FANCY.mp3",
    },
    "22" : {
        title: "The Feels",
        artist: "TWICE",
        genre: "Kpop",
        duration: "3:24",
        track: "TWICE - The Feels.mp3",
    },
    "23" : {
        title: "What is Love",
        artist: "TWICE",
        genre: "Kpop",
        duration: "3:28",
        track: "TWICE - What is Love.mp3",
    },
}
